In [2]:
from airbnb_listing.data_processor import DataProcessor
import pandas as pd
from pathlib import Path

In [4]:
# Import the data
train = pd.read_csv(Path("..",'src','airbnb_listing','data','train.csv'))

In [5]:
train.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,9901706,Cute big one bedroom,1904415,Natalie,Manhattan,Upper West Side,40.77789,-73.97701,Entire home/apt,180,1,0,NaN,NaN,1,0
1,299531,Feel like you never leave your home,1220404,Tom,Brooklyn,East New York,40.66795,-73.89232,Entire home/apt,100,1,119,2019-06-30,1.39,2,289
2,2461439,Pristine Lower East Side Sanctuary,12586492,Sausan,Manhattan,Lower East Side,40.72007,-73.98946,Entire home/apt,133,14,177,2019-05-03,2.82,2,221
3,127387,"Luxe, Spacious 2BR 2BA Nr Trains",23276,Katharine,Brooklyn,Gowanus,40.66862,-73.99260,Entire home/apt,260,30,3,2014-08-04,0.03,1,316
4,629315,1BD brownstone apt in Fort Greene!,2397437,Lauren,Brooklyn,Fort Greene,40.68935,-73.96950,Entire home/apt,120,3,22,2015-10-28,0.27,1,189

In [6]:
data_processor = DataProcessor(train)

In [7]:
processed_data = data_processor.preprocess()

In [8]:
processed_data.head()

,id,is_manhattan,neighbourhood,room_type,minimum_nights,latitude,longitude,days_since_last_review,estimated_listed_months,availability_365,number_of_reviews,calculated_host_listings_count,name,log_price
0,9901706,True,Upper West Side,Entire home/apt,1,40.77789,-73.97701,NaN,NaN,0,0,1,Cute big one bedroom,5.198497
1,299531,False,East New York,Entire home/apt,1,40.66795,-73.89232,2044.0,85.611511,289,119,2,Feel like you never leave your home,4.615121
2,2461439,True,Lower East Side,Entire home/apt,14,40.72007,-73.98946,2102.0,62.765957,221,177,2,Pristine Lower East Side Sanctuary,4.897840
3,127387,False,Gowanus,Entire home/apt,14,40.66862,-73.99260,3835.0,100.000000,316,3,1,"Luxe, Spacious 2BR 2BA Nr Trains",5.564520
4,629315,False,Fort Greene,Entire home/apt,3,40.68935,-73.96950,3385.0,81.481481,189,22,1,1BD brownstone apt in Fort Greene!,4.795791